name: bike-rental-service

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - service-net
    ports:
      - "9090:9090"
    expose:
      - 9090
  bike-manager:
    image: bike-manager
    container_name: bike-manager-01
    networks:
      - service-net
    ports:
      - "9091:8080"
    expose:
      - 9091
  account-manager:
    image: account-manager
    container_name: account-manager-01
    networks:
      - service-net
    ports:
      - "9092:8080"
    expose:
      - 9092
  ride-manager:
    image: ride-manager
    container_name: ride-manager-01
    networks:
      - service-net
    ports:
      - "9093:8080"
    expose:
      - 9093
  auth-service:
    image: auth-service
    container_name: auth-service-01
    networks:
      - service-net
    ports:
      - "9094:8080"
    expose:
      - 9094
  api-gateway:
    image: api-gateway
    container_name: api-gateway-01
    networks:
      - service-net
    ports:
      - "8080:8080"
    expose:
      - 8080
networks:
  service-net:
    driver: bridge
