name: bike-rental-service

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - prometheus
    ports:
      - "9090:9090"
    expose:
      - 9090
  bike-manager:
    image: bike-manager
    container_name: bike-manager-01
    networks:
      - prometheus
    ports:
      - "9091:8080"
    expose:
      - 9091
  account-manager:
    image: account-manager
    container_name: account-manager-01
    networks:
      - prometheus
    ports:
      - "9092:8080"
    expose:
      - 9092
networks:
  prometheus:
    driver: bridge
